[package]
name = "clock-it"
version = "0.1.0"

[site]
site-root = "target/site"
site-pkg-dir = "pkg"

[wasm-opt]
version = "version_124"
args = ["--enable-bulk-memory", "-Oz"]

[build]
target = "wasm32-unknown-unknown"