[phases.setup]
nixPkgs = ["binaryen", "rustup"]

[phases.install]
cmds = [
    "rustup default stable",
    "rustup target add wasm32-unknown-unknown"
]

[phases.build]
cmds = [
    "chmod +x build.sh",
    "./build.sh"
]

[start]
cmd = "./start.sh"