[build]
rustflags = ["-C", "symbol-mangling-version=v0", "-C", "target-feature=+bulk-memory"]

[profile.release]
strip = "symbols"
opt-level = "z"
lto = true
codegen-units = 1

[profile.wasm-release]
inherits = "release"